// sample pipeline
pipeline {
    agent { docker { image 'maven:3.8.3-openjdk-17'} }
    stages {
        stage ( 'Build') {
            echo .... "mvn --version"
            sh 'mvn --version'
        }
        stage ( 'Test') {
            echo ...... 'run the pipeline'
        }
    }
}
