// sample pipeline
pipeline {
    agent {docker { image 'maven:3.8.3'}}
    stages {
        stage ('Build') {
            steps {
				echo "mvn --version"
                sh 'mvn --version'
			}
        }
        stage ('Test') {
            steps {
				echo "run the pipeline"
			}
        }
    }
}
