// sample pipeline
pipeline {
    //agent {any{ image 'maven:3.8.3-openjdk-17'}}
	agent any
	environment {
		mavenHome = tool 'MAVEN'
		PATH = "$mavenHome/bin:$PATH"
	}
    stages {
        stage ('Build') {
            steps {
				echo "mvn --version"
                sh 'mvn --version'
			}
        }
        stage ('Test') {
            steps {
				echo "run the pipeline"
			}
        }
    }
}
